name: New extension submission
description: Submit your extension to the BApp Store for review.
type: Extension
labels: ["Professional"]
body:
- type: markdown
  attributes:
    value: |
      Enter the name of your extension. Choose a clear, descriptive name that reflects what the extension does.
      Find the full BApp Store submission criteria [here](https://portswigger.net/burp/documentation/desktop/extend-burp/extensions/creating/bapp-store-acceptance-criteria).

- type: input
  id: extension_url
  attributes:
    label: Extension URL
    description: Provide the link to the GitHub repository for this extension.
    placeholder: https://github.com/owner/repo
  validations:
    required: true

- type: input
  id: version_number
  attributes:
    label: Version number
    description: Enter the version of your extension.
    placeholder: 1.0.0
  validations:
    required: true

- type: markdown
  attributes:
    value: |
      ### Compatible Burp Editions
      Professional is always included.

      - **Community** - This extension is compatible with Burp Suite Community.
      - **DAST** - This extension is compatible with Burp Suite DAST.
      - **Burp AI** - This extension uses Burp AI features.

- type: checkboxes
  id: product_compatibility
  attributes:
    label: Select additional compatible products and features
    options:
    - label: Community
    - label: DAST
    - label: Burp AI

- type: markdown
  attributes:
    value: |
      ## Author details

- type: input
  id: author_name
  attributes:
    label: Author display name
    description: Enter the name to be displayed as the author of this extension.
  validations:
    required: true

- type: input
  id: contact
  attributes:
    label: Contact details (optional)
    description: |
      You can provide your preferred contact details here in case we need to get in touch.

      **This will be publicly viewable on GitHub.**
    placeholder: ex. email@example.com
  validations:
    required: false

- type: input
  id: discord
  attributes:
    label: Discord username (optional)
    description: |
      If your extension is published, you will be eligible for the BApp Author role on the [PortSwigger Discord server](https://discord.gg/portswigger). This role gives you access to an exclusive channel with other published authors and allows us to tag you in monthly roundups.
      You can enter your Discord username here if you would like this role.

      **Note: This will be publicly viewable on GitHub.**
  validations:
    required: false

- type: checkboxes
  id: confirmation
  attributes:
    label: "I confirm that the following is true:"
    options:
    - label: I have permission from all relevant persons to submit this extension to the BApp Store for public use, under the [terms and conditions of the EULA](https://portswigger.net/legal).
      required: true
    - label: I have read and understood the [submission requirements for the BApp Store](https://portswigger.net/burp/documentation/desktop/extend-burp/extensions/creating/bapp-store-acceptance-criteria).
      required: true

- type: markdown
  attributes:
    value: |
      # Additional information (Optional)
    
- type: textarea
  id: extension_overview
  attributes:
    label: Extension overview
    description: A summary of what your extension does and why it is useful.

- type: textarea
  id: extension_features
  attributes:
    label: Key features
    description: A list of the key features provided by your extension.

- type: textarea
  id: usage_instructions
  attributes:
    label: Usage instructions
    description: Step-by-step instructions for using your extension.

- type: checkboxes
  id: template_identifier
  attributes:
    label: "Template identifier (Internal use only - please ignore)"
    options:
      - label: "template:01-submit-extension"
