name: Update for existing extension
description: Let us know about an update to an existing extension on the BApp Store.
type: Update
body:
- type: markdown
  attributes:
    value: |
      Provide the BApp Store name of the extension you are updating as the title.
      
      Updates are accepted from the parent repository of the PortSwigger fork.
      For any further clarifications, contact us at [bapps@portswigger.net](mailto:bapps@portswigger.net).

- type: input
  id: pr_url
  attributes:
    label: Pull request URL
    description: A link to the pull request for your update.
    placeholder: https://github.com/PortSwigger/repo-name/pull/123
  validations:
    required: true

- type: input
  id: version_number
  attributes:
    label: Version number
    description: The version number of your extension to be displayed.
    placeholder: 1.2.3
  validations:
    required: true

- type: input
  id: author_name
  attributes:
    label: Author display name update
    description: (Optional) Only provide this if you want to change the author name from what is currently displayed on the BApp Store.
  validations:
    required: false

- type: input
  id: contact
  attributes:
    label: Contact Details
    description: |
      (Optional) How can we get in touch with you if we need more info?

      **Note: This information will be publicly viewable on GitHub.**
    placeholder: ex. email@example.com
  validations:
    required: false

- type: input
  id: discord
  attributes:
    label: Discord username
    description: |
      (Optional) If you don't already have the "BApp Author" Discord role on the [PortSwigger Discord server](https://discord.gg/portswigger) and would like it, please provide your Discord username. This role allows us to tag you in monthly roundups and gives you access to an exclusive channel with other published extension authors.

      **Note: This information will be publicly viewable on GitHub.**
  validations:
    required: false

- type: markdown
  attributes:
    value: |
      # Additional information (Optional)
    
- type: textarea
  id: update_summary
  attributes:
    label: Update summary
    description: A summary of the changes made by the update.

- type: textarea
  id: bapp_description
  attributes:
    label: BApp Description update
    description: |
      (Optional) Provide an updated BApp Description for the BApp Store extension information page. This should contain an overview, list of key features, and usage information.

      This description will be displayed on the extension's information page in the BApp Store.
    placeholder: |
      ## Overview
      Brief description of what your extension does...

      ## Key Features
      - Feature 1
      - Feature 2

      ## Usage
      1. First step to use the extension...
      2. Second step...
      3. Third step...

- type: checkboxes
  id: template_identifier
  attributes:
    label: "Template identifier"
    options:
      - label: "template:02-submit-update"
