extension-submission:
  success: |
    Thank you for your BApp Store extension submission!

    Your submission has been added to our review queue.

    We will review your extension as soon as possible. You can track the progress of your submission in our [Extension submissions](https://github.com/orgs/PortSwigger/projects/1) project.

    If you have any questions, please comment on this issue. For urgent matters, contact [bapps@portswigger.net](mailto:bapps@portswigger.net). We do not respond to status update requests via email.

  failure-specific: |
    ❌ Submission failed.

    **Error:** {{ERROR_MESSAGE}}

    Please correct the issue and submit a new request.

  failure-generic: |
    ❌ Submission failed.

    Your submission could not be processed. Please contact [bapps@portswigger.net](mailto:bapps@portswigger.net) for assistance.

update-submission:
  success: |
    Thank you for your extension update!

    Your update has been received and our team has been notified.

    We will review your update as soon as possible. You can track the progress in our [Extension submissions](https://github.com/orgs/PortSwigger/projects/1) project.

    If you have any questions, please comment on this issue. For urgent matters, contact [bapps@portswigger.net](mailto:bapps@portswigger.net).

  failure-specific: |
    ❌ Update submission failed.

    **Error:** {{ERROR_MESSAGE}}

    Please correct the issue and submit a new request.

  failure-generic: |
    ❌ Update submission failed.

    Your update could not be processed. Please contact [bapps@portswigger.net](mailto:bapps@portswigger.net) for assistance.

reopen-issue:
  archived: |
    ⚠️ This issue appears to be archived and has been removed from the project board.

    Our team has been notified and will manually restore it before reopening.

    Please allow some time for this to be processed.
